# Generated by Django 2.2 on 2019-04-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_member_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture_url',
            field=models.TextField(null=True),
        ),
    ]
